### ISSUE TITLE
requirement of zoom 

### ISSUE THREAD

**Issue by jjqcat** [BrutPitt/virtualGizmo3D#2]
Hi , would you support zoom object  or  window rectangle to full view ?

**Comment by BrutPitt** [comment]
Hi, and thanks to write.
I hope I understand correctly your question.

Currently, no... and I would to maintain the tool in abstract layer and independent from graphical frameworks: to use a window/rectangle zoom I should visualize a graphical rectangle on the screen and use graphic functions from OpenGL/DX/Vulkan/... or from 2D frameworks like SDL/SFML/...

But maybe I could make a function available to pass top left and bottom right corners parameters and leave the task to the user to draw the rectangle ad use mouse/key combination
(Or have you a personal way/idea/proposal?)   

Instead, recently (a week ago), I have implemented a proportional pan/zoom speed by PoV distance, to maintain mouse movements constants (and variable pan/zoom speed)... passing also the current PoV distance (or object distance):
https://github.com/BrutPitt/glChAoS.P/commit/62ccc79c52836bb563ff0a243e322a52de5a742e#diff-60af3e263cca88d3bff1913f2fab11ae

It's not yet committed here (but it will be within a few days).
I am testing it in the last **glGhAoS.P** release, and it's currently available only in [**wglChAoS.P**](https://github.com/BrutPitt/glChAoS.P#wglchaosp---webgl2-online-version) WebGL binary release.

But new [vGizmo.h](https://github.com/BrutPitt/glChAoS.P/blob/master/src/src/tools/vGizmo.h) source file is available here: https://github.com/BrutPitt/glChAoS.P/blob/master/src/src/tools

And here you can see as I use the new calls (the way to use is not definitive... is testing phase):
https://github.com/BrutPitt/glChAoS.P/commit/62ccc79c52836bb563ff0a243e322a52de5a742e#diff-253f122f1da3dbe1a1a63e0439a67791
Inside `onMotion(int x, int y)` and `onMouseWheel(int wheel, int direction, int x, int y)` functions

**Comment by jjqcat** [comment]
yes，you're right and understand what I mean.  thanks

**Comment by jjqcat** [comment]
I will be glad to test the library if supports  zoom in by rectangle
